version: '3.0'

services:
  grafana:
    container_name: 'lex-snowflake-datasource'
    platform: "linux/amd64"
    build:
      context: ./.config
      args:
        grafana_image: grafana
        grafana_version: 10.2.4
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/lex-snowflake-datasource
      - ./provisioning:/etc/grafana/provisioning
